
# import data 

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.set_printoptions(suppress=True , linewidth=100 , precision = 2)

In [3]:
raw_data_np=np.genfromtxt("loan-data.csv",delimiter=";",skip_header=1,autostrip=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
raw_data_np[0,:]

array([48010226.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       13.33,
           1184.86,         nan,         nan,         nan,         nan,         nan,     9452.96])

# checking for incomplete data

In [5]:
raw_data_np.shape

(10000, 14)

In [6]:
np.isnan(raw_data_np).sum()

88005

In [7]:
temporary_fill=np.nanmax(raw_data_np) + 1
temporary_mean=np.nanmean(raw_data_np,axis=0)

C:\Users\fareed khaled ibrahe\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: Mean of empty slice
  


In [8]:
temporary_fill

68616520.0

In [9]:
temporary_mean
# el elements el nan de string data 3l4an kda lma gebt el nanmean tala3ha nan

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [10]:
temporary_stats=np.array([np.nanmin(raw_data_np,axis=0) ,
                         temporary_mean,
                         np.nanmax(raw_data_np,axis=0)])

C:\Users\fareed khaled ibrahe\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: All-NaN slice encountered
  """Entry point for launching an IPython kernel.
C:\Users\fareed khaled ibrahe\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: All-NaN slice encountered
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [12]:
temporary_stats[0,:]

array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
             nan,       nan,       nan,       nan,       nan,      0.  ])

In [13]:
temporary_stats.shape

(3, 14)

# splitting the dataset

In [14]:
string_columns=np.argwhere(np.isnan(temporary_mean)).squeeze()
string_columns
# de el columns ele feha string data , 3l4an el nanmean pt3aet el coulmn de ptsawe nan

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [15]:
numeric_columns=np.argwhere(np.isnan(temporary_mean) == False).squeeze()
numeric_columns
# de el coulmns ele feha numeric data , 3l4an el nanmean pta3et el coulmn de ptsawe ar8am 3ade

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [16]:
loan_data_string=np.genfromtxt("loan-data.csv",
                              delimiter=";",
                              skip_header=1,
                              autostrip=True,
                              usecols=string_columns,
                              dtype=np.str_)
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [17]:
loan_data_numeric=np.genfromtxt("loan-data.csv",
                                 delimiter=";",
                                 skip_header=1,
                                 autostrip=True,
                                 usecols=numeric_columns,
                                 
                                )

In [18]:
np.unique(np.isnan(loan_data_numeric),return_counts=True)

(array([False,  True]), array([51995,  8005], dtype=int64))

In [19]:
loan_data_numeric=np.genfromtxt("loan-data.csv",
                                 delimiter=";",
                                 skip_header=1,
                                 autostrip=True,
                                 usecols=numeric_columns,
                                 filling_values=temporary_fill
                                )
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [20]:
temporary_fill

68616520.0

In [21]:
np.unique(np.isnan(loan_data_numeric))

array([False])

In [22]:
loan_data_numeric.shape

(10000, 6)

In [23]:
np.unique(np.isin(loan_data_numeric,temporary_fill),return_counts=True)

(array([False,  True]), array([51995,  8005], dtype=int64))

In [24]:
headear=np.genfromtxt("loan-data.csv",
                       delimiter=";",
                       autostrip=True,
                       skip_footer=raw_data_np.shape[0],
                       dtype=np.str_)
headear

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [25]:
headear_string , headear_number= headear[string_columns] , headear[numeric_columns]

In [26]:
headear_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [27]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [28]:
def check_point(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_var=np.load(file_name+".npz")
    return checkpoint_var
# ana b3mel el checkpoint 3l4an a3mel copy la el dataset ele ana 48al 3leha kol 4oya 3l4an lo 7asel 8alat yb2a m3ay a5er nos5a
# reliable practice when we need to clean or preprocess many parts of dataset 

In [29]:
checkpoint_test=check_point("checkpoint_test",headear_string,loan_data_string)

In [30]:
checkpoint_test["header"]

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [31]:
checkpoint_test["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [32]:
np.array_equal(checkpoint_test["data"] , loan_data_string)

True

In [33]:
headear_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [34]:
headear_string[0]='issue_date'

In [35]:
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [36]:
loan_data_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [37]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [38]:
loan_data_string[:,0]=np.chararray.strip(loan_data_string[:,0],"-15")

In [39]:
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [40]:
monthes=["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == monthes[i] , i ,loan_data_string[:,0])
    

In [41]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [42]:
headear_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [43]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [44]:
statues_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])
# ahm 7aga fe el loan_status column ano y4of 7alet el person fe sdad el 8ard good wala bad 
# 3l4an kda a7na hn2sem el column da la two category wa nde la el two category doal numbers 3l4an n3rf
# nt3amel m3ahom 
## fhoa hna 7at el strings ele ptdoal 3la bad statues fe array

In [45]:
np.isin(loan_data_string[:,1],statues_bad)

array([False, False, False, ..., False, False, False])

In [46]:
np.unique(np.isin(loan_data_string[:,1],statues_bad),return_counts=True)

(array([False,  True]), array([9313,  687], dtype=int64))

In [47]:
loan_data_string[:,1]= np.where(np.isin(loan_data_string[:,1],statues_bad),0,1)

In [48]:
loan_data_string[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

In [49]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

In [50]:
headear_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [51]:
loan_data_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [52]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [53]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2],' months')

In [54]:
np.unique(loan_data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [55]:
loan_data_string[:,2] = np.where(loan_data_string[:,2] == "",
                        60,
                        loan_data_string[:,2])

In [56]:
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

In [57]:
headear_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [58]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [59]:
np.unique(loan_data_string[:,4])
# hena a7na la2ena an el column el grade wa el sub_grade related be b3d 
# fkda ana a2der asta5dem column wa7ed mnhom 3l4an bydolo 3la nafs el data 
# y3ne masaln fe colum el sub_grade el row ele feah A1,A2,A3,A4,A5 da m3nah
# an nafs column grade fe nafs el row ptsawe A 
# fkda ana a2der a4eal coulmn grade 3l4an sub_grade yo3taber feah nafs el data 

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [60]:
np.unique(loan_data_string[:,3])[1:]
# 3amelt indexing mn awel el 1 34an a4eal el empty values mn el array

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [61]:
for i in np.unique(loan_data_string[:,3])[1:]:
    print(i)

A
B
C
D
E
F
G


In [62]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4]=np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i ), 
                                   i+'5',
                                   loan_data_string[:,4])

In [63]:
np.unique(loan_data_string[:,4])
# el empty values m4 kolha at4alet 3l4an fe rows el grade feha empty bardo wa ana 
# ma handlet4 el case de fe el loop ele 4aletle el empty values fo2 

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [64]:
np.unique(loan_data_string[:,4],return_counts=True)
# ana 3ande 9 rows bas ele el sub_grade fehom empty fa momken a4elhom 3ade 
# bas ana m4 h3mel kda ana h3mel category gdeda la el empty values de 

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [65]:
loan_data_string[:,4]=np.where(loan_data_string[:,4] == '', 
         "H1" ,
         loan_data_string[:,4])

In [66]:
np.unique(loan_data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [67]:
loan_data_string= np.delete(loan_data_string , 3 ,axis=1)
# 4elna coulmn grade 3l4an yo3tbar nafs el data mogoda fe el sub_grade zay ma 4ra7na fo2

In [68]:
loan_data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [69]:
headear_string= np.delete(headear_string , 3)
# 4elna asm column grade mn el header_string

In [70]:
headear_string[3]

'sub_grade'

In [71]:
np.unique(loan_data_string[:,3]).shape

(36,)

In [72]:
dic_keys=list(np.unique(loan_data_string[:,3]))
dic_vlaues=list(range(1,np.unique(loan_data_string[:,3]).shape[0]+1))
dict_sub_grade=dict(zip(dic_keys,dic_vlaues))

In [73]:
np.unique(loan_data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [74]:
for i in dict_sub_grade :
    print(i +" " +np.str_(dict_sub_grade[i]))

A1 1
A2 2
A3 3
A4 4
A5 5
B1 6
B2 7
B3 8
B4 9
B5 10
C1 11
C2 12
C3 13
C4 14
C5 15
D1 16
D2 17
D3 18
D4 19
D5 20
E1 21
E2 22
E3 23
E4 24
E5 25
F1 26
F2 27
F3 28
F4 29
F5 30
G1 31
G2 32
G3 33
G4 34
G5 35
H1 36


In [75]:
for i in dict_sub_grade :
    loan_data_string[:,3]=np.where(loan_data_string[:,3] == i , dict_sub_grade[i], loan_data_string[:,3])

In [76]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [77]:
headear_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [78]:
loan_data_string[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [79]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [80]:
loan_data_string[:,4]=np.where( (loan_data_string[:,4] == '') |  (loan_data_string[:,4] == 'Not Verified'),0,1)

In [81]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

In [82]:
headear_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [83]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [84]:
loan_data_string[:,5]=np.chararray.strip(loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [85]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [86]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [87]:
np.array_equal(loan_data_string[:,5].astype(dtype=np.int32),loan_data_numeric[:,0])

True

In [88]:
loan_data_string=np.delete(loan_data_string,5,axis=1)

In [89]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [90]:
loan_data_string.shape

(10000, 6)

In [91]:
headear_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [92]:
headear_string= np.delete(headear_string,5)

In [93]:
headear_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [94]:
headear_string[5]="state_address"

In [95]:
headear_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [96]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [97]:
states_names,states_count= np.unique(loan_data_string[:,5],return_counts=True)

In [98]:
states_names

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [99]:
states_count

array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
         84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
        341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
         17,  216,  148,   49,   27], dtype=int64)

In [100]:
states_count_sorted=np.argsort(-states_count)
states_names[states_count_sorted] , states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [101]:
loan_data_string[:,5]=np.where(loan_data_string[:,5]=="",
                              0,
                              loan_data_string[:,5])

In [102]:
states_west=np.array(["WA","OR","CA","NV","ID","MT","WY","UT","CO","AZ","NM","HI","AK"])
states_south=np.array(["TX","OK","AR","LA","MS","AL","TN","KY","FL","GA","SC","NC","VA","WV","MD","DE","DC"])
states_miswest=np.array(["ND","SD","NE","KS","MN","IA","MO","WI","IL","IN","MI","OH"])
states_east=np.array(["PA","NY","NJ","CT","MA","VT","NH","ME","RI"])

In [103]:
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_west),1,loan_data_string[:,5])
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_south),2,loan_data_string[:,5])
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_miswest),3,loan_data_string[:,5] )
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_east),4,loan_data_string[:,5])

In [104]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [105]:
loan_data_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [106]:
loan_data_string=loan_data_string.astype(np.int32)

In [107]:
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [108]:
checkpoint_strings=check_point("chekpoint-strtings",headear_string,loan_data_string)

In [109]:
checkpoint_strings

In [110]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [111]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [112]:
numeric_columns

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [113]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [114]:
temporary_stats[:,numeric_columns]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [115]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [116]:
np.isnan(loan_data_numeric).sum()

0

In [117]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [118]:
temporary_fill

68616520.0

In [119]:
np.unique(np.isin(loan_data_numeric,temporary_fill))

array([False,  True])

In [120]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

0

In [121]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [122]:
numeric_columns

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [123]:
temporary_stats[:,numeric_columns]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [124]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [125]:
temporary_stats[0,numeric_columns[2]]

1000.0

In [126]:
loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2] == temporary_fill ,
                                temporary_stats[0,numeric_columns[2]],
                                loan_data_numeric[:,2])
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [127]:
np.isin(loan_data_numeric[:,2],temporary_fill).sum()

0

In [128]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [129]:
numeric_columns

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [130]:
numeric_columns[1]

2

In [131]:
loan_data_numeric.shape

(10000, 6)

In [132]:
list_=[1,3,4,5]
for i in list_:
    loan_data_numeric[:,i]=np.where(loan_data_numeric[:,i] == temporary_fill,
                                   temporary_stats[2,numeric_columns[i]],
                                   loan_data_numeric[:,i])

In [133]:
for i in range(5):
    print(np.isnan(loan_data_numeric[i+1] == temporary_fill).sum())

0
0
0
0
0


In [134]:
EUR_USD=np.genfromtxt("Eur-USD.csv",delimiter=",", autostrip=True ,skip_header=True)
EUR_USD

array([[1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [135]:
Eure_header=np.genfromtxt("Eur-USD.csv",delimiter=",",autostrip=True,skip_footer=EUR_USD.shape[0],
                         dtype=np.str_)
Eure_header


array(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='<U6')

In [136]:
EUR_USD.shape

(12, 5)

In [137]:
EUR_USD=np.genfromtxt("Eur-USD.csv",delimiter=",",autostrip=True,skip_header=True,usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [138]:
headear_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [139]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [140]:
np.unique(loan_data_string[:,0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
exchange_rate = loan_data_string[:,0]

for i in range(1,13):
    exchange_rate= np.where(exchange_rate  == i ,
                            EUR_USD[i-1],
                            exchange_rate)
    
exchange_rate= np.where(exchange_rate == 0 ,
                        np.mean(EUR_USD),
                        exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [142]:
exchange_rate.shape

(10000,)

In [143]:
loan_data_numeric.shape

(10000, 6)

In [144]:
exchange_rate=np.reshape(exchange_rate,(10000,1)) 

In [145]:
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [146]:
np.hstack((loan_data_numeric,exchange_rate))

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [147]:
np.hstack((loan_data_numeric,exchange_rate)).shape

(10000, 7)

In [148]:
loan_data_numeric= np.hstack((loan_data_numeric,exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [149]:
loan_data_numeric.shape

(10000, 7)

In [150]:
headear_number.shape

(6,)

In [151]:
np.array(["exchange_rate"])

array(['exchange_rate'], dtype='<U13')

In [152]:
headear_number=np.concatenate((headear_number,np.array(["exchange_rate"])))

In [153]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

### a7ne fe ele gay 3ayzean n7ol mn dolar la euro ( USD to EUR ) 

In [154]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [155]:
columns_dolar=np.array([1,2,4,5])
### de el columns ele h7olha mn Eru la USD 

In [156]:
loan_data_numeric[:,columns_dolar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [157]:
for i in columns_dolar:
    loan_data_numeric= np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6] ,(10000,1))))

In [158]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [159]:
loan_data_numeric.shape

(10000, 11)

In [160]:
header_addational= np.array([column_name+' _EUR' for column_name in headear_number[columns_dolar]])

In [161]:
header_addational

array(['loan_amnt _EUR', 'funded_amnt _EUR', 'installment _EUR', 'total_pymnt _EUR'], dtype='<U16')

In [162]:
headear_number=np.concatenate((headear_number,header_addational))

In [163]:
headear_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt _EUR', 'funded_amnt _EUR', 'installment _EUR', 'total_pymnt _EUR'], dtype='<U19')

In [164]:
headear_number[columns_dolar]=np.array([column_name + " _usd" for column_name in headear_number[columns_dolar]])

In [165]:
headear_number

array(['id', 'loan_amnt _usd', 'funded_amnt _usd', 'int_rate', 'installment _usd',
       'total_pymnt _usd', 'exchange_rate', 'loan_amnt _EUR', 'funded_amnt _EUR',
       'installment _EUR', 'total_pymnt _EUR'], dtype='<U19')

In [166]:
columns_index_order=[0,1,7,2,8,3,4,9,5,10,6]

In [167]:
headear_number[columns_index_order]

array(['id', 'loan_amnt _usd', 'loan_amnt _EUR', 'funded_amnt _usd', 'funded_amnt _EUR',
       'int_rate', 'installment _usd', 'installment _EUR', 'total_pymnt _usd', 'total_pymnt _EUR',
       'exchange_rate'], dtype='<U19')

In [168]:
headear_number=headear_number[columns_index_order]

In [169]:
headear_number

array(['id', 'loan_amnt _usd', 'loan_amnt _EUR', 'funded_amnt _usd', 'funded_amnt _EUR',
       'int_rate', 'installment _usd', 'installment _EUR', 'total_pymnt _usd', 'total_pymnt _EUR',
       'exchange_rate'], dtype='<U19')

In [170]:
loan_data_numeric[:,5]

array([9452.96, 4679.7 , 1969.83, ..., 2185.64, 3199.4 ,  301.9 ])

In [171]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [172]:
loan_data_numeric[:,5]

array([94.53, 46.8 , 19.7 , ..., 21.86, 31.99,  3.02])

In [173]:
checkpint_numeric=check_point("checkpoint-numeric",headear_number,loan_data_numeric)

In [174]:
checkpint_numeric['header'] , checkpint_numeric['data']

(array(['id', 'loan_amnt _usd', 'loan_amnt _EUR', 'funded_amnt _usd', 'funded_amnt _EUR',
        'int_rate', 'installment _usd', 'installment _EUR', 'total_pymnt _usd', 'total_pymnt _EUR',
        'exchange_rate'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
        [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
        [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
        [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
        [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]]))

### end of video 14

### at this part we will compine the numeric dataset with the string dataset

In [175]:
checkpoint_strings["data"].shape

(10000, 6)

In [176]:
checkpint_numeric["data"].shape

(10000, 11)

In [177]:
loan_data=np.hstack((checkpint_numeric['data'],checkpoint_strings['data']))

In [178]:
loan_data.shape

(10000, 17)

In [179]:
np.isnan(loan_data).sum()

0

In [180]:
header_full=np.concatenate((checkpint_numeric['header'],checkpoint_strings['header']))

In [181]:
header_full.shape

(17,)

In [182]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [183]:
loan_data

array([[  373332.,     9950.,     1000., ...,       21.,        0.,        1.],
       [  575239.,    12000.,    12000., ...,       25.,        1.,        2.],
       [  707689.,    10000.,    10000., ...,       13.,        1.,        0.],
       ...,
       [68614880.,     5600.,     5600., ...,        8.,        1.,        1.],
       [68615915.,     4000.,     4000., ...,       10.,        1.,        2.],
       [68616519.,    21600.,    21600., ...,        3.,        0.,        2.]])

In [184]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [185]:
loan_data=np.vstack((header_full,loan_data))

In [186]:
loan_data

array([['id', 'loan_amnt _usd', 'loan_amnt _EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '1000.0', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '12000.0', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5600.0', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '4000.0', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '21600.0', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [187]:
np.savetxt("loan_data_preprocessed.csv",loan_data,fmt="%s",delimiter=',')

In [190]:
#np.load("loan_data_preprocessed.csv")
pd.read_csv("loan_data_preprocessed.csv")

id  loan_amnt _usd  loan_amnt _EUR  funded_amnt _usd  \
0       373332.0          9950.0          1000.0             18.25   
1       575239.0         12000.0         12000.0             20.99   
2       707689.0         10000.0         10000.0             13.66   
3       709828.0         27200.0         27200.0             28.99   
4       849994.0         11400.0         11400.0             28.99   
...          ...             ...             ...               ...   
9995  68603178.0         14000.0         14000.0             28.99   
9996  68604253.0         20000.0         20000.0             28.99   
9997  68614880.0          5600.0          5600.0             28.99   
9998  68615915.0          4000.0          4000.0             28.99   
9999  68616519.0         21600.0         21600.0             28.99   

      funded_amnt _EUR  int_rate  installment _usd  installment _EUR  \
0               360.97   10.7282          1.100897       9038.082814   
1               324.58    9.5975          1.100897      10900.200379   
2               340.13   37.2625          1.120536       8924.299805   
3               553.87  419.1362          1.100897      24707.120859   
4               376.09   37.5360          1.083025      10526.076489   
...                ...       ...               ...               ...   
9995            421.61  419.1362          1.093398      12804.119629   
9996            631.26    0.0000          1.093398      18291.599470   
9997            180.18    0.0000          1.093398       5121.647852   
9998            131.87    0.0000          1.093398       3658.319894   
9999            666.85    0.0000          1.093398      19754.927428   

      total_pymnt _usd  total_pymnt _EUR  exchange_rate  issue_date  \
0           908.350032        327.887111     974.496081        10.0   
1         10900.200379        294.832253     871.788943        10.0   
2          8924.299805        303.542209    3325.417215         2.0   
3         24707.120859        503.107832   38072.238051        10.0   
4         10526.076489        347.258957    3465.849185         3.0   
...                ...               ...            ...         ...   
9995      12804.119629        385.596063   38333.357469        12.0   
9996      18291.599470        577.337754       0.000000        12.0   
9997       5121.647852        164.789020       0.000000        12.0   
9998       3658.319894        120.605661       0.000000        12.0   
9999      19754.927428        609.887655       0.000000        12.0   

      loan_status  term  sub_grade  verification_status  state_address  
0             1.0  36.0       21.0                  0.0            1.0  
1             1.0  60.0       25.0                  1.0            2.0  
2             1.0  36.0       13.0                  1.0            0.0  
3             1.0  60.0        6.0                  0.0            4.0  
4             0.0  36.0       10.0                  0.0            1.0  
...           ...   ...        ...                  ...            ...  
9995          1.0  36.0        1.0                  0.0            1.0  
9996          1.0  36.0        6.0                  0.0            2.0  
9997          1.0  36.0        8.0                  1.0            1.0  
9998          1.0  36.0       10.0                  1.0            2.0  
9999          1.0  36.0        3.0                  0.0            2.0  

[10000 rows x 17 columns]